<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <SupportedPlatform Include="browser" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HelseLoop.Shared.UI\HelseLoop.Shared.UI.csproj" />
    <ProjectReference Include="..\HelseLoop.Infrastructure.Browser\HelseLoop.Infrastructure.Browser.csproj" />
  </ItemGroup>

</Project>
