<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>HelseLoop.SharedUI</RootNamespace>
    <AssemblyName>HelseLoop.SharedUI</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HelseLoop.Application\HelseLoop.Application.csproj" />
  </ItemGroup>

</Project>
